import pandas as pd
import re

# File paths
CSV_FILE = '/Users/yassinebenayed/Desktop/cleaning/Export_cleaned.csv'
OUTPUT_FILE = '/Users/yassinebenayed/Desktop/cleaning/Export_cleaned_remaining.csv'

# List of companies that were successfully sent (from the output)
SENT_COMPANIES = [
    "S3I",
    "KPIT Engineering",
    "Soft Assistance & Développement (SAD)",
    "ISIMS",
    "SfaxSoft",
    "Isims",
    "Cisen Computer",
    "All Soft Multimedia",
    "syberno",
    "Raba7ni",
    "FLOUKETNA",
    "Ste Elkaouthar de Huile d'Olive",
    "Lab. ATMS (Advanced Technologies For Medicine and Signals)",
    "Méga Chip Solution",
    "BINetCom – Business Innovative Networks and Communications",
    "Group chimique sfax",
    "Institut Supérieur d'Informatique et de Multimédia de Sfax (ISIMS)",
    "Association Tunisienne de l'espace Tunsa",
    "Sociéte SwiftCode",
    "Aura Dynamic",
    "SOFTPRO",
    "Polysoft informatique",
    "nexoratech",
    "Internet Soft",
    "Almes sfax",
    "Infotech Consulting Services",
    "Pixel Pro",
    "ITANIS",
    "Be Synchro",
    "MedCity",
    "malloulinova",
    "Reach On",
    "KPIT",
    "habemus! Solutions",
    "ZNet-IT",
    "ANNAHR Services",
    "Aquila Digital",
    "Actia Aeronautic Services",
    "ZETA-BOX",
    "DigiLab Solutions",
    "yesmind technologies",
    "Mega Pixel AB",
    "Unidev",
    "ECO CODE",
    "Informatique Net",
    "informatique net",
    "STARK",
    "Sofrecom Tunisie",
    "Azartech",
    "Zone Seven média",
    "SOFT PRO",
    "IBS",
    "ahmed trigui consulting",
    "Onbotics",
    "TunKubeOps",
    "SolEthik Energy",
    "BePrimeTech",
    "sfax silver star agent Mercedes agréé  le moteur",
    "Fogits International",
    "Polyclinic Erriadh",
    "Sté LAGID Olive Soft Tunisie",
    "Net Advisor",
    "TufraTech",
    "LEADERTEC ENGINEERING",
    "Optimalogistic",
    "SOPIQ",
    "CES-Lab",
    "IRSTechnologie",
    "Odyssey Design Agency",
    "STEG",
    "Centre INET formation",
    "PROXIMIND",
    "PROGED INTERNATIONAL",
    "ScaleX Innovation",
    "DIGIXI",
    "Amilcar petrolum operation",
    "Clinisys ERP",
    "Patcoin",
    "IODEV",
    "Société webvue",
    "ITPIDIA",
    "ALL SOFT MULTIMEDIA",
    "Climate innov digital",
    "IPSOFT",
    "tansik group",
    "SCPC Comptoir Hammami",
    "GETS Company",
    "ImpactDev",
    "Univers Equipement",
    "Preventis",
    "A2SOFT",
    "Bizexperience",
    "Oxygène Technologies",
    "Yassine Masmoudi",
    "Stark",
    "BIAT",
    "P.M.C",
    "alpha Etiquettes",
    "Engineering & Consuling",
    "Djagora foundation",
    "high water technology",
    "TN SMART IOT",
    "Société des ingénieurs pour les affaires \"siaf\"",
    "societe les abattoirs Chahia",
    "Flash Digital Marketing",
    "21 c' Digital",
    "exypnos",
    "Media Center Developpment",
    "STE PERFAXIS",
    "ZEN Group Sfax",
    "Smart Ways Innovation",
    "21C'Digital",
    "Amicale du Personnel de la SEREPT",
    "Winkcloud-Solutions",
    "Centre de recherche en Numérique de Sfax",
    "Souma Technologies Ever",
    "TopCode Softwares",
    "Polyclinique Essalama",
    "MTD GROUP",
    "Mobelite Labs",
    "Novatis",
    "Hopital Hbib Bourgiba Sfax",
    "TechInventors Sci-Kids Technology Hub",
    "Faculté des sciences de Sfax",
    "Xilyor",
    "Lynx-ERP",
    "PROCAN",
    "MAS group",
    "future proof",
    "codily software",
    "PSI Petrole Services Industries",
    "Advanced Computer Solutions",
    "3T",
    "Lunar TC",
    "My partner ISC",
    "STEROS",
    "CoConsult",
]

# Read CSV
df = pd.read_csv(CSV_FILE, sep=';')

print(f"Original records: {len(df)}")
print(f"Records to remove: {len(SENT_COMPANIES)}")

# Remove sent companies - case insensitive match
df_remaining = df[~df["Nom de l'entreprise"].isin(SENT_COMPANIES)]

print(f"Remaining records: {len(df_remaining)}")
print(f"Removed: {len(df) - len(df_remaining)}")

# Save remaining
df_remaining.to_csv(OUTPUT_FILE, sep=';', index=False, quoting=1)

print(f"\n✓ Filtered CSV saved to: {OUTPUT_FILE}")
print(f"\nRemaining companies to email: {len(df_remaining)}")
